config/routes.rb
Rails.application.routes.draw do

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :name, :email, :password, :password_confirmation

  validates :name, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 8 }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Usuario criado com sucesso!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = "Usuario atualizado com sucesso!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy
    flash[:notice] = "usuario deletado com sucesso!"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<% @user.errors.full_messages.each do |a| %>
  <li><%= a %></li>
<% end %>

<%= form_for (@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>

  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @user.each do |a| %>

  <%= a.id %>
  <%= a.name %>
  <%= a.email %>
  <br>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p><%= link_to "Deletar usuário", user_path, :method => :delete %></p>
<p><%= link_to "Editar usuário", edit_user_path %></p>

<p><%= @user.id %></p>
<p><%= @user.name %></p>
<p><%= @user.email %></p>